.\" This is a man page for the deepmethod command.
.
.\" Written by Konstantin Kozlov, St.Petersburg, Russia , 17 Feb 2015.
.TH DEEPMETHOD 1 "2/17/2015" "(C) St.Petersburg Polytechnic University." "Konstantin Kozlov"
.
.SH NAME
deepmethod \- Optimize using DEEP.
.
.SH SYNOPSIS
.B deepmethod
.
.SH DESCRIPTION
The
.B deepmethod
calls DEEP metho.
.
.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default is one bit.
.
.SH BUGS
The command name should have been chosen more carefully
to reflect its purpose.
.
.SH AUTHOR
Konstantin Kozlov <mackoel@gmail.com>
.
.SH SEE ALSO
.greet(1)